version: '3'

services:
  mongodb:
    # azure
    image: reserva.azurecr.io/mongodb
    container_name: mongodb_1
    build:
      context: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - express-mongo
    expose:
      - 27017

  express:
    # azure
    image: reserva.azurecr.io/express
    container_name: express_1
    build:
      context: express
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - express-mongo
    expose:
      - 5000

  mongo-express:
    #azure
    container_name: mongo-express_1
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb_1:27017
      - ME_CONFIG_MONGODB_SERVER=mongodb_1
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - express-mongo

# react:
#   container_name: react_1
#   build:
#     context: react-app
#   ports:
#     - "3000:3000"
#   depends_on:
#     - express
#   networks:
#     - express-mongo
#   expose:
#     - 3000

volumes:
  mongodb-data:
networks:
  express-mongo:
